findUser:
  type: User
  args:
    userId: UserPayload
  resolve: 游눌./resolvers/findUser.ts

views:
  type: Views
  resolve: 游눌./resolvers/views.ts

views2:
  type: Views
  resolve: 游눌./resolvers/views.ts
views3:
  type: Views
  resolve: 游눌./resolvers/views.ts