name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@avantageusa'
      - run: npm install
        env:
          AVANTAGE_REGISTRY_TOKEN: ${{ secrets.AVANTAGE_REGISTRY_TOKEN }}
      - run: npm run lint --if-present
        env:
          AVANTAGE_REGISTRY_TOKEN: ${{ secrets.AVANTAGE_REGISTRY_TOKEN }}
      - run: npm test
        env:
          AVANTAGE_REGISTRY_TOKEN: ${{ secrets.AVANTAGE_REGISTRY_TOKEN }}
